<?php

namespace Database\Seeders\tenant;

use App\Models\Tenants\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CountriesSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        $countries = [
            ['iso_code_a3' => 'AFG', 'iso_code_a2' => 'AF', 'name' => 'Afghanistan'],
            ['iso_code_a3' => 'ALB', 'iso_code_a2' => 'AL', 'name' => 'Albania'],
            ['iso_code_a3' => 'DZA', 'iso_code_a2' => 'DZ', 'name' => 'Algeria'],
            ['iso_code_a3' => 'AND', 'iso_code_a2' => 'AD', 'name' => 'Andorra'],
            ['iso_code_a3' => 'AGO', 'iso_code_a2' => 'AO', 'name' => 'Angola'],
            ['iso_code_a3' => 'ATG', 'iso_code_a2' => 'AG', 'name' => 'Antigua and Barbuda'],
            ['iso_code_a3' => 'ARG', 'iso_code_a2' => 'AR', 'name' => 'Argentina'],
            ['iso_code_a3' => 'ARM', 'iso_code_a2' => 'AM', 'name' => 'Armenia'],
            ['iso_code_a3' => 'AUS', 'iso_code_a2' => 'AU', 'name' => 'Australia'],
            ['iso_code_a3' => 'AUT', 'iso_code_a2' => 'AT', 'name' => 'Austria'],
            ['iso_code_a3' => 'AZE', 'iso_code_a2' => 'AZ', 'name' => 'Azerbaijan'],
            ['iso_code_a3' => 'BHS', 'iso_code_a2' => 'BS', 'name' => 'Bahamas'],
            ['iso_code_a3' => 'BHR', 'iso_code_a2' => 'BH', 'name' => 'Bahrain'],
            ['iso_code_a3' => 'BGD', 'iso_code_a2' => 'BD', 'name' => 'Bangladesh'],
            ['iso_code_a3' => 'BRB', 'iso_code_a2' => 'BB', 'name' => 'Barbados'],
            ['iso_code_a3' => 'BLR', 'iso_code_a2' => 'BY', 'name' => 'Belarus'],
            ['iso_code_a3' => 'BEL', 'iso_code_a2' => 'BE', 'name' => 'Belgium'],
            ['iso_code_a3' => 'BLZ', 'iso_code_a2' => 'BZ', 'name' => 'Belize'],
            ['iso_code_a3' => 'BEN', 'iso_code_a2' => 'BJ', 'name' => 'Benin'],
            ['iso_code_a3' => 'BTN', 'iso_code_a2' => 'BT', 'name' => 'Bhutan'],
            ['iso_code_a3' => 'BOL', 'iso_code_a2' => 'BO', 'name' => 'Bolivia'],
            ['iso_code_a3' => 'BIH', 'iso_code_a2' => 'BA', 'name' => 'Bosnia and Herzegovina'],
            ['iso_code_a3' => 'BWA', 'iso_code_a2' => 'BW', 'name' => 'Botswana'],
            ['iso_code_a3' => 'BRA', 'iso_code_a2' => 'BR', 'name' => 'Brazil'],
            ['iso_code_a3' => 'BRN', 'iso_code_a2' => 'BN', 'name' => 'Brunei Darussalam'],
            ['iso_code_a3' => 'BGR', 'iso_code_a2' => 'BG', 'name' => 'Bulgaria'],
            ['iso_code_a3' => 'BFA', 'iso_code_a2' => 'BF', 'name' => 'Burkina Faso'],
            ['iso_code_a3' => 'BDI', 'iso_code_a2' => 'BI', 'name' => 'Burundi'],
            ['iso_code_a3' => 'CPV', 'iso_code_a2' => 'CV', 'name' => 'Cabo Verde'],
            ['iso_code_a3' => 'KHM', 'iso_code_a2' => 'KH', 'name' => 'Cambodia'],
            ['iso_code_a3' => 'CMR', 'iso_code_a2' => 'CM', 'name' => 'Cameroon'],
            ['iso_code_a3' => 'CAN', 'iso_code_a2' => 'CA', 'name' => 'Canada'],
            ['iso_code_a3' => 'CAF', 'iso_code_a2' => 'CF', 'name' => 'Central African Republic'],
            ['iso_code_a3' => 'TCD', 'iso_code_a2' => 'TD', 'name' => 'Chad'],
            ['iso_code_a3' => 'CHL', 'iso_code_a2' => 'CL', 'name' => 'Chile'],
            ['iso_code_a3' => 'CHN', 'iso_code_a2' => 'CN', 'name' => 'China'],
            ['iso_code_a3' => 'COL', 'iso_code_a2' => 'CO', 'name' => 'Colombia'],
            ['iso_code_a3' => 'COM', 'iso_code_a2' => 'KM', 'name' => 'Comoros'],
            ['iso_code_a3' => 'COG', 'iso_code_a2' => 'CG', 'name' => 'Congo (Brazzaville)'],
            ['iso_code_a3' => 'COD', 'iso_code_a2' => 'CD', 'name' => 'Congo (Kinshasa)'],
            ['iso_code_a3' => 'CRI', 'iso_code_a2' => 'CR', 'name' => 'Costa Rica'],
            ['iso_code_a3' => 'CIV', 'iso_code_a2' => 'CI', 'name' => "Côte d'Ivoire"],
            ['iso_code_a3' => 'HRV', 'iso_code_a2' => 'HR', 'name' => 'Croatia'],
            ['iso_code_a3' => 'CUB', 'iso_code_a2' => 'CU', 'name' => 'Cuba'],
            ['iso_code_a3' => 'CYP', 'iso_code_a2' => 'CY', 'name' => 'Cyprus'],
            ['iso_code_a3' => 'CZE', 'iso_code_a2' => 'CZ', 'name' => 'Czech Republic'],
            ['iso_code_a3' => 'DNK', 'iso_code_a2' => 'DK', 'name' => 'Denmark'],
            ['iso_code_a3' => 'DJI', 'iso_code_a2' => 'DJ', 'name' => 'Djibouti'],
            ['iso_code_a3' => 'DMA', 'iso_code_a2' => 'DM', 'name' => 'Dominica'],
            ['iso_code_a3' => 'DOM', 'iso_code_a2' => 'DO', 'name' => 'Dominican Republic'],
            ['iso_code_a3' => 'ECU', 'iso_code_a2' => 'EC', 'name' => 'Ecuador'],
            ['iso_code_a3' => 'EGY', 'iso_code_a2' => 'EG', 'name' => 'Egypt'],
            ['iso_code_a3' => 'SLV', 'iso_code_a2' => 'SV', 'name' => 'El Salvador'],
            ['iso_code_a3' => 'GNQ', 'iso_code_a2' => 'GQ', 'name' => 'Equatorial Guinea'],
            ['iso_code_a3' => 'ERI', 'iso_code_a2' => 'ER', 'name' => 'Eritrea'],
            ['iso_code_a3' => 'EST', 'iso_code_a2' => 'EE', 'name' => 'Estonia'],
            ['iso_code_a3' => 'SWZ', 'iso_code_a2' => 'SZ', 'name' => 'Eswatini'],
            ['iso_code_a3' => 'ETH', 'iso_code_a2' => 'ET', 'name' => 'Ethiopia'],
            ['iso_code_a3' => 'FJI', 'iso_code_a2' => 'FJ', 'name' => 'Fiji'],
            ['iso_code_a3' => 'FIN', 'iso_code_a2' => 'FI', 'name' => 'Finland'],
            ['iso_code_a3' => 'FRA', 'iso_code_a2' => 'FR', 'name' => 'France'],
            ['iso_code_a3' => 'GAB', 'iso_code_a2' => 'GA', 'name' => 'Gabon'],
            ['iso_code_a3' => 'GMB', 'iso_code_a2' => 'GM', 'name' => 'Gambia'],
            ['iso_code_a3' => 'GEO', 'iso_code_a2' => 'GE', 'name' => 'Georgia'],
            ['iso_code_a3' => 'DEU', 'iso_code_a2' => 'DE', 'name' => 'Germany'],
            ['iso_code_a3' => 'GHA', 'iso_code_a2' => 'GH', 'name' => 'Ghana'],
            ['iso_code_a3' => 'GRC', 'iso_code_a2' => 'GR', 'name' => 'Greece'],
            ['iso_code_a3' => 'GRD', 'iso_code_a2' => 'GD', 'name' => 'Grenada'],
            ['iso_code_a3' => 'GTM', 'iso_code_a2' => 'GT', 'name' => 'Guatemala'],
            ['iso_code_a3' => 'GIN', 'iso_code_a2' => 'GN', 'name' => 'Guinea'],
            ['iso_code_a3' => 'GNB', 'iso_code_a2' => 'GW', 'name' => 'Guinea-Bissau'],
            ['iso_code_a3' => 'GUY', 'iso_code_a2' => 'GY', 'name' => 'Guyana'],
            ['iso_code_a3' => 'HTI', 'iso_code_a2' => 'HT', 'name' => 'Haiti'],
            ['iso_code_a3' => 'HND', 'iso_code_a2' => 'HN', 'name' => 'Honduras'],
            ['iso_code_a3' => 'HUN', 'iso_code_a2' => 'HU', 'name' => 'Hungary'],
            ['iso_code_a3' => 'ISL', 'iso_code_a2' => 'IS', 'name' => 'Iceland'],
            ['iso_code_a3' => 'IND', 'iso_code_a2' => 'IN', 'name' => 'India'],
            ['iso_code_a3' => 'IDN', 'iso_code_a2' => 'ID', 'name' => 'Indonesia'],
            ['iso_code_a3' => 'IRN', 'iso_code_a2' => 'IR', 'name' => 'Iran'],
            ['iso_code_a3' => 'IRQ', 'iso_code_a2' => 'IQ', 'name' => 'Iraq'],
            ['iso_code_a3' => 'IRL', 'iso_code_a2' => 'IE', 'name' => 'Ireland'],
            ['iso_code_a3' => 'ISR', 'iso_code_a2' => 'IL', 'name' => 'Israel'],
            ['iso_code_a3' => 'ITA', 'iso_code_a2' => 'IT', 'name' => 'Italy'],
            ['iso_code_a3' => 'JAM', 'iso_code_a2' => 'JM', 'name' => 'Jamaica'],
            ['iso_code_a3' => 'JPN', 'iso_code_a2' => 'JP', 'name' => 'Japan'],
            ['iso_code_a3' => 'JOR', 'iso_code_a2' => 'JO', 'name' => 'Jordan'],
            ['iso_code_a3' => 'KAZ', 'iso_code_a2' => 'KZ', 'name' => 'Kazakhstan'],
            ['iso_code_a3' => 'KEN', 'iso_code_a2' => 'KE', 'name' => 'Kenya'],
            ['iso_code_a3' => 'KIR', 'iso_code_a2' => 'KI', 'name' => 'Kiribati'],
            ['iso_code_a3' => 'KWT', 'iso_code_a2' => 'KW', 'name' => 'Kuwait'],
            ['iso_code_a3' => 'KGZ', 'iso_code_a2' => 'KG', 'name' => 'Kyrgyzstan'],
            ['iso_code_a3' => 'LAO', 'iso_code_a2' => 'LA', 'name' => 'Lao PDR'],
            ['iso_code_a3' => 'LVA', 'iso_code_a2' => 'LV', 'name' => 'Latvia'],
            ['iso_code_a3' => 'LBN', 'iso_code_a2' => 'LB', 'name' => 'Lebanon'],
            ['iso_code_a3' => 'LSO', 'iso_code_a2' => 'LS', 'name' => 'Lesotho'],
            ['iso_code_a3' => 'LBR', 'iso_code_a2' => 'LR', 'name' => 'Liberia'],
            ['iso_code_a3' => 'LBY', 'iso_code_a2' => 'LY', 'name' => 'Libya'],
            ['iso_code_a3' => 'LIE', 'iso_code_a2' => 'LI', 'name' => 'Liechtenstein'],
            ['iso_code_a3' => 'LTU', 'iso_code_a2' => 'LT', 'name' => 'Lithuania'],
            ['iso_code_a3' => 'LUX', 'iso_code_a2' => 'LU', 'name' => 'Luxembourg'],
            ['iso_code_a3' => 'MDG', 'iso_code_a2' => 'MG', 'name' => 'Madagascar'],
            ['iso_code_a3' => 'MWI', 'iso_code_a2' => 'MW', 'name' => 'Malawi'],
            ['iso_code_a3' => 'MYS', 'iso_code_a2' => 'MY', 'name' => 'Malaysia'],
            ['iso_code_a3' => 'MDV', 'iso_code_a2' => 'MV', 'name' => 'Maldives'],
            ['iso_code_a3' => 'MLI', 'iso_code_a2' => 'ML', 'name' => 'Mali'],
            ['iso_code_a3' => 'MLT', 'iso_code_a2' => 'MT', 'name' => 'Malta'],
            ['iso_code_a3' => 'MHL', 'iso_code_a2' => 'MH', 'name' => 'Marshall Islands'],
            ['iso_code_a3' => 'MRT', 'iso_code_a2' => 'MR', 'name' => 'Mauritania'],
            ['iso_code_a3' => 'MUS', 'iso_code_a2' => 'MU', 'name' => 'Mauritius'],
            ['iso_code_a3' => 'MEX', 'iso_code_a2' => 'MX', 'name' => 'Mexico'],
            ['iso_code_a3' => 'FSM', 'iso_code_a2' => 'FM', 'name' => 'Micronesia'],
            ['iso_code_a3' => 'MDA', 'iso_code_a2' => 'MD', 'name' => 'Moldova'],
            ['iso_code_a3' => 'MCO', 'iso_code_a2' => 'MC', 'name' => 'Monaco'],
            ['iso_code_a3' => 'MNG', 'iso_code_a2' => 'MN', 'name' => 'Mongolia'],
            ['iso_code_a3' => 'MNE', 'iso_code_a2' => 'ME', 'name' => 'Montenegro'],
            ['iso_code_a3' => 'MAR', 'iso_code_a2' => 'MA', 'name' => 'Morocco'],
            ['iso_code_a3' => 'MOZ', 'iso_code_a2' => 'MZ', 'name' => 'Mozambique'],
            ['iso_code_a3' => 'MMR', 'iso_code_a2' => 'MM', 'name' => 'Myanmar'],
            ['iso_code_a3' => 'NAM', 'iso_code_a2' => 'NA', 'name' => 'Namibia'],
            ['iso_code_a3' => 'NRU', 'iso_code_a2' => 'NR', 'name' => 'Nauru'],
            ['iso_code_a3' => 'NPL', 'iso_code_a2' => 'NP', 'name' => 'Nepal'],
            ['iso_code_a3' => 'NLD', 'iso_code_a2' => 'NL', 'name' => 'Netherlands'],
            ['iso_code_a3' => 'NZL', 'iso_code_a2' => 'NZ', 'name' => 'New Zealand'],
            ['iso_code_a3' => 'NIC', 'iso_code_a2' => 'NI', 'name' => 'Nicaragua'],
            ['iso_code_a3' => 'NER', 'iso_code_a2' => 'NE', 'name' => 'Niger'],
            ['iso_code_a3' => 'NGA', 'iso_code_a2' => 'NG', 'name' => 'Nigeria'],
            ['iso_code_a3' => 'PRK', 'iso_code_a2' => 'KP', 'name' => 'North Korea'],
            ['iso_code_a3' => 'MKD', 'iso_code_a2' => 'MK', 'name' => 'North Macedonia'],
            ['iso_code_a3' => 'NOR', 'iso_code_a2' => 'NO', 'name' => 'Norway'],
            ['iso_code_a3' => 'OMN', 'iso_code_a2' => 'OM', 'name' => 'Oman'],
            ['iso_code_a3' => 'PAK', 'iso_code_a2' => 'PK', 'name' => 'Pakistan'],
            ['iso_code_a3' => 'PLW', 'iso_code_a2' => 'PW', 'name' => 'Palau'],
            ['iso_code_a3' => 'PSE', 'iso_code_a2' => 'PS', 'name' => 'Palestine'],
            ['iso_code_a3' => 'PAN', 'iso_code_a2' => 'PA', 'name' => 'Panama'],
            ['iso_code_a3' => 'PNG', 'iso_code_a2' => 'PG', 'name' => 'Papua New Guinea'],
            ['iso_code_a3' => 'PRY', 'iso_code_a2' => 'PY', 'name' => 'Paraguay'],
            ['iso_code_a3' => 'PER', 'iso_code_a2' => 'PE', 'name' => 'Peru'],
            ['iso_code_a3' => 'PHL', 'iso_code_a2' => 'PH', 'name' => 'Philippines'],
            ['iso_code_a3' => 'POL', 'iso_code_a2' => 'PL', 'name' => 'Poland'],
            ['iso_code_a3' => 'PRT', 'iso_code_a2' => 'PT', 'name' => 'Portugal'],
            ['iso_code_a3' => 'QAT', 'iso_code_a2' => 'QA', 'name' => 'Qatar'],
            ['iso_code_a3' => 'ROU', 'iso_code_a2' => 'RO', 'name' => 'Romania'],
            ['iso_code_a3' => 'RUS', 'iso_code_a2' => 'RU', 'name' => 'Russian Federation'],
            ['iso_code_a3' => 'RWA', 'iso_code_a2' => 'RW', 'name' => 'Rwanda'],
            ['iso_code_a3' => 'KNA', 'iso_code_a2' => 'KN', 'name' => 'Saint Kitts and Nevis'],
            ['iso_code_a3' => 'LCA', 'iso_code_a2' => 'LC', 'name' => 'Saint Lucia'],
            ['iso_code_a3' => 'VCT', 'iso_code_a2' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
            ['iso_code_a3' => 'WSM', 'iso_code_a2' => 'WS', 'name' => 'Samoa'],
            ['iso_code_a3' => 'SMR', 'iso_code_a2' => 'SM', 'name' => 'San Marino'],
            ['iso_code_a3' => 'STP', 'iso_code_a2' => 'ST', 'name' => 'Sao Tome and Principe'],
            ['iso_code_a3' => 'SAU', 'iso_code_a2' => 'SA', 'name' => 'Saudi Arabia'],
            ['iso_code_a3' => 'SEN', 'iso_code_a2' => 'SN', 'name' => 'Senegal'],
            ['iso_code_a3' => 'SRB', 'iso_code_a2' => 'RS', 'name' => 'Serbia'],
            ['iso_code_a3' => 'SYC', 'iso_code_a2' => 'SC', 'name' => 'Seychelles'],
            ['iso_code_a3' => 'SLE', 'iso_code_a2' => 'SL', 'name' => 'Sierra Leone'],
            ['iso_code_a3' => 'SGP', 'iso_code_a2' => 'SG', 'name' => 'Singapore'],
            ['iso_code_a3' => 'SVK', 'iso_code_a2' => 'SK', 'name' => 'Slovakia'],
            ['iso_code_a3' => 'SVN', 'iso_code_a2' => 'SI', 'name' => 'Slovenia'],
            ['iso_code_a3' => 'SLB', 'iso_code_a2' => 'SB', 'name' => 'Solomon Islands'],
            ['iso_code_a3' => 'SOM', 'iso_code_a2' => 'SO', 'name' => 'Somalia'],
            ['iso_code_a3' => 'ZAF', 'iso_code_a2' => 'ZA', 'name' => 'South Africa'],
            ['iso_code_a3' => 'KOR', 'iso_code_a2' => 'KR', 'name' => 'South Korea'],
            ['iso_code_a3' => 'SSD', 'iso_code_a2' => 'SS', 'name' => 'South Sudan'],
            ['iso_code_a3' => 'ESP', 'iso_code_a2' => 'ES', 'name' => 'Spain'],
            ['iso_code_a3' => 'LKA', 'iso_code_a2' => 'LK', 'name' => 'Sri Lanka'],
            ['iso_code_a3' => 'SDN', 'iso_code_a2' => 'SD', 'name' => 'Sudan'],
            ['iso_code_a3' => 'SUR', 'iso_code_a2' => 'SR', 'name' => 'Suriname'],
            ['iso_code_a3' => 'SWE', 'iso_code_a2' => 'SE', 'name' => 'Sweden'],
            ['iso_code_a3' => 'CHE', 'iso_code_a2' => 'CH', 'name' => 'Switzerland'],
            ['iso_code_a3' => 'SYR', 'iso_code_a2' => 'SY', 'name' => 'Syrian Arab Republic'],
            ['iso_code_a3' => 'TJK', 'iso_code_a2' => 'TJ', 'name' => 'Tajikistan'],
            ['iso_code_a3' => 'TZA', 'iso_code_a2' => 'TZ', 'name' => 'Tanzania'],
            ['iso_code_a3' => 'THA', 'iso_code_a2' => 'TH', 'name' => 'Thailand'],
            ['iso_code_a3' => 'TLS', 'iso_code_a2' => 'TL', 'name' => 'Timor-Leste'],
            ['iso_code_a3' => 'TGO', 'iso_code_a2' => 'TG', 'name' => 'Togo'],
            ['iso_code_a3' => 'TON', 'iso_code_a2' => 'TO', 'name' => 'Tonga'],
            ['iso_code_a3' => 'TTO', 'iso_code_a2' => 'TT', 'name' => 'Trinidad and Tobago'],
            ['iso_code_a3' => 'TUN', 'iso_code_a2' => 'TN', 'name' => 'Tunisia'],
            ['iso_code_a3' => 'TUR', 'iso_code_a2' => 'TR', 'name' => 'Türkiye'],
            ['iso_code_a3' => 'TKM', 'iso_code_a2' => 'TM', 'name' => 'Turkmenistan'],
            ['iso_code_a3' => 'TUV', 'iso_code_a2' => 'TV', 'name' => 'Tuvalu'],
            ['iso_code_a3' => 'UGA', 'iso_code_a2' => 'UG', 'name' => 'Uganda'],
            ['iso_code_a3' => 'UKR', 'iso_code_a2' => 'UA', 'name' => 'Ukraine'],
            ['iso_code_a3' => 'ARE', 'iso_code_a2' => 'AE', 'name' => 'United Arab Emirates'],
            ['iso_code_a3' => 'GBR', 'iso_code_a2' => 'GB', 'name' => 'United Kingdom'],
            ['iso_code_a3' => 'USA', 'iso_code_a2' => 'US', 'name' => 'United States'],
            ['iso_code_a3' => 'URY', 'iso_code_a2' => 'UY', 'name' => 'Uruguay'],
            ['iso_code_a3' => 'UZB', 'iso_code_a2' => 'UZ', 'name' => 'Uzbekistan'],
            ['iso_code_a3' => 'VUT', 'iso_code_a2' => 'VU', 'name' => 'Vanuatu'],
            ['iso_code_a3' => 'VEN', 'iso_code_a2' => 'VE', 'name' => 'Venezuela'],
            ['iso_code_a3' => 'VNM', 'iso_code_a2' => 'VN', 'name' => 'Viet Nam'],
            ['iso_code_a3' => 'YEM', 'iso_code_a2' => 'YE', 'name' => 'Yemen'],
            ['iso_code_a3' => 'ZMB', 'iso_code_a2' => 'ZM', 'name' => 'Zambia'],
            ['iso_code_a3' => 'ZWE', 'iso_code_a2' => 'ZW', 'name' => 'Zimbabwe'],
        ];


        foreach ($countries as $key => $country) {
            Country::create([
                'iso_code' => $country['code'],
                'name' => $country['name'],
            ]);
        }
    }
}
