<?php


return [
    'depreciation_end_date' => 'Depreciation end date',
    'notice_date' => 'Contract notice date',
    'end_date' => 'Contract end date',
    'planned_at' => 'Intervention planned at',
    'next_maintenance_date' => 'Next maintenance date',
    'end_warranty_date' => 'End warranty date',
    'disclaimer' => 'This notification was automatically generated by your facility management system. If you have any questions, contact your administrator.',


];
