<?php


return [
    'title' => 'Notification|Notifications',
    'depreciation_end_date' => 'Depreciation end date',
    'depreciation_end_date_subtitle' => 'An asset depreciation is about to expire:',
    'depreciation_end_date_description' => 'After this date, the asset will be fully depreciated.',
    'notice_date' => 'Contract notice date',
    'notice_date_subtitle' => 'A contract is about to expire:',
    'notice_date_description' => 'We recommend taking the necessary steps to renew or terminate this contract.',
    'end_date' => 'Contract end date',
    'end_date_subtitle' => 'A contract is about to expire:',
    'end_date_description' => 'We recommend taking the necessary steps to renew or terminate this contract.',
    'planned_at' => 'Intervention planned at',
    'planned_at_subtitle' => 'An intervention is scheduled soon:',
    'planned_at_description' => 'We recommend preparing the necessary arrangements for the intervention.',
    'next_maintenance_date' => 'Next maintenance date',
    'next_maintenance_date_subtitle' => 'A maintenance is scheduled soon:',
    'next_maintenance_date_description' => 'Please ensure this maintenance is organized within the expected timeframe.',
    'end_warranty_date' => 'End of warranty date',
    'end_warranty_date_subtitle' => 'A warranty is about to expire:',
    'end_warranty_date_description' => 'After this date, you will no longer be covered by the warranty.',
    'disclaimer' => 'This notification was automatically generated by your facility management system. If you have any questions, please contact your administrator.',



];
